import type { NewGiftInput } from "@/lib/firestore/gifts";

/**
 * Sugestão de catálogo "divertido" (cotas/contribuições, sem produto físico).
 * Usado pelo botão de importação rápida no painel admin — o casal edita ou
 * remove o que quiser depois.
 */
export const funGiftsPreset: NewGiftInput[] = [
  {
    name: "Aviãozinho de dinheiro",
    description: "Contribua com uma grana pro nosso aviãozinho — cada real ajuda a decolar nessa nova vida.",
    icon: "✈️",
    price: 50,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Vale Netflix",
    description: "Ajude o casal a manter a assinatura do streaming em dia (Netflix, Prime, HBO... você escolhe!).",
    icon: "🍿",
    price: 45,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Uber para não pagar multa de rodízio",
    description: "Uma corrida de Uber a menos infringindo o rodízio municipal.",
    icon: "🚕",
    price: 40,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "1º mês de jantar do casal",
    description: "Garanta que o primeiro mês de casados tenha jantar na mesa (ou no delivery).",
    icon: "🍽️",
    price: 150,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Aluguel de bebê para treinamento",
    description: "Um dia de 'aluguel' de sobrinho ou afilhado pra gente treinar antes da coisa ficar séria.",
    icon: "👶",
    price: 80,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Vale terapia",
    description: "Pra manter a sanidade em dia depois de organizar (e sobreviver) ao casamento.",
    icon: "🧘",
    price: 120,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Passeio de balão",
    description: "Um passeio de balão pra esquecer a fatura do cartão que vem por aí.",
    icon: "🎈",
    price: 400,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Ajuda nos 14 meses de aluguel",
    description: "Sabe aquele aluguel de 14 meses? Cada contribuição ajuda a fechar a conta.",
    icon: "🏠",
    price: 200,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Procedimentos estéticos do casal",
    description: "Pra gente continuar lindo e chegar arrasando nas próximas festas.",
    icon: "💅",
    price: 180,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Alexa",
    description: "Pra noiva (ou noivo) ter mais alguém pra chamar toda hora além do cônjuge.",
    icon: "🔊",
    price: 250,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Cota do robô aspirador",
    description: "Ajude a evitar a fadiga de casados varrendo a casa.",
    icon: "🤖",
    price: 100,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Patrocine a cervejinha",
    description: "Garanta que a cervejinha gelada nunca vai faltar.",
    icon: "🍻",
    price: 60,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Vale churrasco",
    description: "Garanta sua vaga no próximo churrasco lá em casa.",
    icon: "🍖",
    price: 90,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Um mês de aula de dança",
    description: "Pra gente arrasar no TikTok (ou pelo menos não pisar no pé um do outro).",
    icon: "💃",
    price: 130,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Balança",
    description: "Pra gente ficar de olho e não sair muito da forma depois do casamento.",
    icon: "⚖️",
    price: 70,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Chá para a ansiedade",
    description: "Pra aguentar a ansiedade de dizer sim (e de arrumar a casa antes das visitas).",
    icon: "🍵",
    price: 35,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Open bar na festa",
    description: "Ajude a manter o open bar rolando solto até o fim da festa.",
    icon: "🍹",
    price: 100,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Espirro em Paris",
    description: "Contribua com a nossa lua de mel — todo espirro em Paris conta.",
    icon: "🗼",
    price: 300,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Apoio psicológico",
    description: "Pra sobreviver emocionalmente ao pós-casamento com dignidade.",
    icon: "🧠",
    price: 150,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
  {
    name: "Combo de controles de TV",
    description: "Um controle pra cada um, pra nunca mais brigar por causa disso.",
    icon: "📺",
    price: 60,
    type: "cota",
    purchaseLink: "",
    pixKey: "",
    category: "Divertido",
    imageUrl: "",
  },
];
